<?xml version="1.0"?>
<package format="3">
  <name>workpieces_detection_subsystem</name>
  <version>0.0.0</version>
  <description>Workpieces detection subsystem for the MOTOMAN human collaboration system.</description>

  <maintainer email="yamamoto@rsdlab.jp">Yukiya Yamamto</maintainer>
  <author email="yamamoto@rsdlab.jp">Yukiya Yamamto</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Service interface generation -->
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Message / service dependencies -->
  <depend>collaboration_manipulation_message</depend>

  <!-- Python node dependencies -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>aruco_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
